### ISSUE TITLE
Install fails if database exists

### ISSUE THREAD

**Issue by jrogelstad** [jrogelstad/featherbone#30]
If an empty database is created ahead of time (instead of featherbone creating it itself) and you run node install against it, it will throw an error:

C:\Users\john\Documents\GitHub\featherbone>node install
(node:6992) UnhandledPromiseRejectionWarning: error: relation "$settings" does not exist
    at Connection.parseE (C:\Users\john\Documents\GitHub\featherbone\node_modules\pg\lib\connection.js:554:11)
    at Connection.parseMessage (C:\Users\john\Documents\GitHub\featherbone\node_modules\pg\lib\connection.js:379:19)
    at Socket.<anonymous> (C:\Users\john\Documents\GitHub\featherbone\node_modules\pg\lib\connection.js:119:22)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17)
(node:6992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6992) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jrogelstad** [comment]
[Fixed](https://github.com/jrogelstad/featherbone/commit/2259ed9f102244cad8a3510175ba884eed7ae4cb).
